"""initial: capture existing schema

Revision ID: 8c798042e646
Revises: 
Create Date: 2026-04-09 12:29:48.123258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c798042e646'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowed_domains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('is_wildcard', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target', sa.String(length=100), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployed_apps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_username', sa.String(length=50), nullable=False),
    sa.Column('app_name', sa.String(length=100), nullable=False),
    sa.Column('app_url', sa.String(length=255), nullable=True),
    sa.Column('pod_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=True),
    sa.Column('app_port', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pod_name')
    )
    op.create_index(op.f('ix_deployed_apps_owner_username'), 'deployed_apps', ['owner_username'], unique=False)
    op.create_table('file_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_audit_logs_username'), 'file_audit_logs', ['username'], unique=False)
    op.create_table('governed_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('classification', sa.String(length=20), nullable=True),
    sa.Column('classification_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('ttl_days', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('classified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governed_files_username'), 'governed_files', ['username'], unique=False)
    op.create_table('infra_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('policy', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('prompt_audit_conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'session_id', 'message_type', 'timestamp', name='uq_conversation_msg')
    )
    op.create_index(op.f('ix_prompt_audit_conversations_session_id'), 'prompt_audit_conversations', ['session_id'], unique=False)
    op.create_index(op.f('ix_prompt_audit_conversations_username'), 'prompt_audit_conversations', ['username'], unique=False)
    op.create_table('prompt_audit_flags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('flagged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('prompt_excerpt', sa.Text(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=50), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_audit_flags_username'), 'prompt_audit_flags', ['username'], unique=False)
    op.create_table('prompt_audit_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('audit_date', sa.Date(), nullable=False),
    sa.Column('total_prompts', sa.Integer(), nullable=True),
    sa.Column('total_chars', sa.BigInteger(), nullable=True),
    sa.Column('category_counts', sa.JSON(), nullable=True),
    sa.Column('flagged_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'audit_date', name='uq_audit_user_date')
    )
    op.create_index(op.f('ix_prompt_audit_summary_username'), 'prompt_audit_summary', ['username'], unique=False)
    op.create_table('proxy_access_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('allowed', sa.Boolean(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_proxy_access_logs_created_at', 'proxy_access_logs', ['created_at'], unique=False)
    op.create_index('ix_proxy_access_logs_user_id', 'proxy_access_logs', ['user_id'], unique=False)
    op.create_table('security_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('policy', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('shared_datasets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_username', sa.String(length=50), nullable=False),
    sa.Column('dataset_name', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_username', 'dataset_name', name='uq_owner_dataset')
    )
    op.create_index(op.f('ix_shared_datasets_owner_username'), 'shared_datasets', ['owner_username'], unique=False)
    op.create_table('shared_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author_username', sa.String(length=50), nullable=True),
    sa.Column('author_name', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.String(length=50), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_username', sa.String(length=50), nullable=True),
    sa.Column('skill_name', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('skill_type', sa.String(length=20), nullable=True),
    sa.Column('skill_dir_name', sa.String(length=100), nullable=True),
    sa.Column('install_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_skills_author_username'), 'shared_skills', ['author_username'], unique=False)
    op.create_index(op.f('ix_shared_skills_is_approved'), 'shared_skills', ['is_approved'], unique=False)
    op.create_index('ix_shared_skills_owner', 'shared_skills', ['owner_username'], unique=False)
    op.create_table('survey_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_username', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_templates_owner_username'), 'survey_templates', ['owner_username'], unique=False)
    op.create_table('token_quota_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('template_name', sa.String(length=50), nullable=False),
    sa.Column('cost_limit_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('refresh_cycle', sa.String(length=20), nullable=False),
    sa.Column('is_unlimited', sa.Boolean(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_quota_assignments_username'), 'token_quota_assignments', ['username'], unique=False)
    op.create_table('token_quota_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('cost_limit_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('refresh_cycle', sa.String(length=20), nullable=False),
    sa.Column('is_unlimited', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('token_usage_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('input_tokens', sa.BigInteger(), nullable=True),
    sa.Column('output_tokens', sa.BigInteger(), nullable=True),
    sa.Column('total_tokens', sa.BigInteger(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cost_krw', sa.Integer(), nullable=True),
    sa.Column('session_minutes', sa.Integer(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'usage_date')
    )
    op.create_table('token_usage_hourly',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.BigInteger(), nullable=True),
    sa.Column('output_tokens', sa.BigInteger(), nullable=True),
    sa.Column('total_tokens', sa.BigInteger(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cost_krw', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'usage_date', 'slot', name='uq_slot_user_date_slot')
    )
    op.create_table('two_factor_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_two_factor_codes_username'), 'two_factor_codes', ['username'], unique=False)
    op.create_index('ix_two_factor_codes_username_created', 'two_factor_codes', ['username', 'created_at'], unique=False)
    op.create_table('user_bots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('bot_token_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('bot_token_hash', sa.String(length=64), nullable=False),
    sa.Column('bot_username', sa.String(length=100), nullable=True),
    sa.Column('webhook_secret', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_bots_bot_token_hash'), 'user_bots', ['bot_token_hash'], unique=True)
    op.create_index(op.f('ix_user_bots_user_id'), 'user_bots', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('region_name', sa.String(length=50), nullable=True),
    sa.Column('team_name', sa.String(length=50), nullable=True),
    sa.Column('job_name', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('pod_ttl', sa.String(length=10), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('storage_retention', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('can_deploy_apps', sa.Boolean(), nullable=True),
    sa.Column('security_policy', sa.JSON(), nullable=True),
    sa.Column('infra_policy', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('app_acl',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('grant_type', sa.String(length=10), nullable=False),
    sa.Column('grant_value', sa.String(length=100), nullable=False),
    sa.Column('granted_by', sa.String(length=50), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['deployed_apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_acl_app_id'), 'app_acl', ['app_id'], unique=False)
    op.create_index('ix_app_acl_grant', 'app_acl', ['app_id', 'grant_type', 'grant_value', 'revoked_at'], unique=False)
    op.create_table('app_views',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('viewer_user_id', sa.String(length=50), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['deployed_apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_app_views_app_id_viewed_at', 'app_views', ['app_id', 'viewed_at'], unique=False)
    op.create_table('file_share_acl',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('share_type', sa.String(length=20), nullable=False),
    sa.Column('share_target', sa.String(length=100), nullable=False),
    sa.Column('granted_by', sa.String(length=50), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['shared_datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_share_acl_dataset_id'), 'file_share_acl', ['dataset_id'], unique=False)
    op.create_table('skill_installs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('uninstalled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['shared_skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_skill_installs_skill', 'skill_installs', ['skill_id'], unique=False)
    op.create_index('ix_skill_installs_user', 'skill_installs', ['username'], unique=False)
    op.create_table('survey_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('target_username', sa.String(length=50), nullable=False),
    sa.Column('telegram_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('current_question_idx', sa.Integer(), nullable=True),
    sa.Column('partial_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['survey_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_survey_assignments_target', 'survey_assignments', ['target_username', 'status'], unique=False)
    op.create_table('terminal_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('pod_name', sa.String(length=100), nullable=True),
    sa.Column('pod_status', sa.String(length=20), nullable=True),
    sa.Column('session_type', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terminated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proxy_secret', sa.String(length=64), nullable=True),
    sa.Column('pod_token_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pod_name')
    )
    op.create_table('survey_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('responder_username', sa.String(length=50), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['survey_assignments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id')
    )
    op.create_index(op.f('ix_survey_responses_responder_username'), 'survey_responses', ['responder_username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_responses_responder_username'), table_name='survey_responses')
    op.drop_table('survey_responses')
    op.drop_table('terminal_sessions')
    op.drop_index('ix_survey_assignments_target', table_name='survey_assignments')
    op.drop_table('survey_assignments')
    op.drop_index('ix_skill_installs_user', table_name='skill_installs')
    op.drop_index('ix_skill_installs_skill', table_name='skill_installs')
    op.drop_table('skill_installs')
    op.drop_index(op.f('ix_file_share_acl_dataset_id'), table_name='file_share_acl')
    op.drop_table('file_share_acl')
    op.drop_index('ix_app_views_app_id_viewed_at', table_name='app_views')
    op.drop_table('app_views')
    op.drop_index('ix_app_acl_grant', table_name='app_acl')
    op.drop_index(op.f('ix_app_acl_app_id'), table_name='app_acl')
    op.drop_table('app_acl')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_bots_user_id'), table_name='user_bots')
    op.drop_index(op.f('ix_user_bots_bot_token_hash'), table_name='user_bots')
    op.drop_table('user_bots')
    op.drop_index('ix_two_factor_codes_username_created', table_name='two_factor_codes')
    op.drop_index(op.f('ix_two_factor_codes_username'), table_name='two_factor_codes')
    op.drop_table('two_factor_codes')
    op.drop_table('token_usage_hourly')
    op.drop_table('token_usage_daily')
    op.drop_table('token_quota_templates')
    op.drop_index(op.f('ix_token_quota_assignments_username'), table_name='token_quota_assignments')
    op.drop_table('token_quota_assignments')
    op.drop_index(op.f('ix_survey_templates_owner_username'), table_name='survey_templates')
    op.drop_table('survey_templates')
    op.drop_index('ix_shared_skills_owner', table_name='shared_skills')
    op.drop_index(op.f('ix_shared_skills_is_approved'), table_name='shared_skills')
    op.drop_index(op.f('ix_shared_skills_author_username'), table_name='shared_skills')
    op.drop_table('shared_skills')
    op.drop_index(op.f('ix_shared_datasets_owner_username'), table_name='shared_datasets')
    op.drop_table('shared_datasets')
    op.drop_table('security_templates')
    op.drop_index('ix_proxy_access_logs_user_id', table_name='proxy_access_logs')
    op.drop_index('ix_proxy_access_logs_created_at', table_name='proxy_access_logs')
    op.drop_table('proxy_access_logs')
    op.drop_index(op.f('ix_prompt_audit_summary_username'), table_name='prompt_audit_summary')
    op.drop_table('prompt_audit_summary')
    op.drop_index(op.f('ix_prompt_audit_flags_username'), table_name='prompt_audit_flags')
    op.drop_table('prompt_audit_flags')
    op.drop_index(op.f('ix_prompt_audit_conversations_username'), table_name='prompt_audit_conversations')
    op.drop_index(op.f('ix_prompt_audit_conversations_session_id'), table_name='prompt_audit_conversations')
    op.drop_table('prompt_audit_conversations')
    op.drop_table('infra_templates')
    op.drop_index(op.f('ix_governed_files_username'), table_name='governed_files')
    op.drop_table('governed_files')
    op.drop_index(op.f('ix_file_audit_logs_username'), table_name='file_audit_logs')
    op.drop_table('file_audit_logs')
    op.drop_index(op.f('ix_deployed_apps_owner_username'), table_name='deployed_apps')
    op.drop_table('deployed_apps')
    op.drop_table('audit_logs')
    op.drop_table('allowed_domains')
    # ### end Alembic commands ###
